/**
 * User Models
 * Defines TypeScript interfaces for user data structures.
 * Includes types for user entities, DTOs for create/update operations, and login credentials.
 */

import { v4 as uuidv4 } from 'uuid'; // Assuming you have uuid installed

/**
 * Base user interface with all database fields.
 * Includes password_hash for authentication purposes.
 * 
 * @interface BaseUser
 * @property {string} [id] - UUID, optional for creation (auto-generated by database)
 * @property {string} username - Unique username (3-30 alphanumeric characters)
 * @property {string} email - Unique email address
 * @property {string} password_hash - Bcrypt hashed password (never exposed to client)
 * @property {string | null} [first_name] - User's first name (optional)
 * @property {string | null} [last_name] - User's last name (optional)
 * @property {'user' | 'admin'} role - User role for authorization
 * @property {string | null} [avatar_url] - URL to user's avatar image (optional)
 * @property {Date} [created_at] - Timestamp of user creation
 * @property {Date} [updated_at] - Timestamp of last update
 */
export interface BaseUser {
  id?: string; // UUID, optional for creation
  username: string;
  email: string;
  password_hash: string;
  first_name?: string | null;
  last_name?: string | null;
  role: 'user' | 'admin';
  avatar_url?: string | null;
  created_at?: Date;
  updated_at?: Date;
}

/**
 * User interface for database records.
 * Extends BaseUser with required ID field.
 * 
 * @interface User
 * @extends {BaseUser}
 */
export interface User extends BaseUser {
    id: string; // Ensure ID is present when fetching from DB
}

/**
 * Data Transfer Object for creating a new user.
 * Password is provided in plain text and will be hashed before storage.
 * Role defaults to 'user' if not specified.
 * 
 * @interface CreateUserDto
 * @property {string} username - Unique username (3-30 alphanumeric characters)
 * @property {string} email - Unique email address
 * @property {string} password - Plain text password (min 8 chars, uppercase, lowercase, number, special char)
 * @property {string} [first_name] - User's first name (optional)
 * @property {string} [last_name] - User's last name (optional)
 * @property {'user' | 'admin'} [role] - User role, defaults to 'user'
 * @property {string} [avatar_url] - URL to user's avatar image (optional)
 * 
 * @example
 * const newUser: CreateUserDto = {
 *   username: 'johndoe',
 *   email: 'john@example.com',
 *   password: 'SecurePass123!',
 *   first_name: 'John',
 *   last_name: 'Doe',
 *   role: 'user'
 * };
 */
export interface CreateUserDto {
  username: string;
  email: string;
  password: string; // Plain text password for input, will be hashed
  first_name?: string;
  last_name?: string;
  role?: 'user' | 'admin'; // Default to 'user'
  avatar_url?: string;
}

/**
 * Data Transfer Object for updating an existing user.
 * All fields are optional (partial update supported).
 * Password should be updated through separate endpoint for security.
 * Role updates typically restricted to admin users.
 * 
 * @interface UpdateUserDto
 * @property {string} [username] - Unique username (3-30 alphanumeric characters)
 * @property {string} [email] - Unique email address
 * @property {string | null} [first_name] - User's first name
 * @property {string | null} [last_name] - User's last name
 * @property {'user' | 'admin'} [role] - User role (admin-only operation)
 * @property {string | null} [avatar_url] - URL to user's avatar image
 * 
 * @example
 * const updates: UpdateUserDto = {
 *   first_name: 'Jane',
 *   avatar_url: 'https://example.com/avatar.jpg'
 * };
 */
export interface UpdateUserDto {
  username?: string;
  email?: string;
  // Password should not be updatable directly via a general update; use specific change password endpoint
  first_name?: string | null;
  last_name?: string | null;
  role?: 'user' | 'admin'; // Typically only admins can change roles, or users their own profile limited fields
  avatar_url?: string | null;
}

/**
 * Data Transfer Object for user login.
 * Contains credentials for authentication.
 * 
 * @interface LoginDto
 * @property {string} email - User's email address
 * @property {string} password - User's plain text password
 * 
 * @example
 * const credentials: LoginDto = {
 *   email: 'john@example.com',
 *   password: 'SecurePass123!'
 * };
 */
export interface LoginDto {
  email: string;
  password: string;
}

